# Generated by Django 2.2 on 2019-04-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='post',
            name='times_visited',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('a', 'Классическая архитектура'), ('b', 'Современная архитектура'), ('c', 'Скульптура'), ('d', 'Музеи'), ('e', 'Театры'), ('f', 'Улицы, площади'), ('g', 'Парки')], max_length=1),
        ),
    ]
