# Generated by Django 2.2 on 2019-04-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0002_auto_20190404_1918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['city', 'type'], 'verbose_name': 'Достопримечательность'},
        ),
        migrations.AlterField(
            model_name='post',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('a', 'Классическая архитектура'), ('b', 'Современная архитектура'), ('c', 'Скульптура'), ('d', 'Музеи'), ('e', 'Театры'), ('f', 'Улицы, площади'), ('g', 'Парки')], max_length=1, verbose_name='Вид'),
        ),
    ]
