# Generated by Django 2.2 on 2019-04-14 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0003_auto_20190405_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/')),
                ('sight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temp.Post')),
            ],
        ),
    ]
