# Generated by Django 2.2 on 2019-04-14 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0004_postimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimage',
            options={'verbose_name': 'Фото'},
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('a', 'Классическая архитектура'), ('b', 'Современная архитектура'), ('c', 'Скульптура'), ('d', 'Музеи'), ('e', 'Театры'), ('f', 'Улицы, площади'), ('g', 'Природа, парки')], max_length=1, verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='sight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temp.Post', verbose_name='Достопримечательность'),
        ),
    ]
